### ISSUE TITLE
more settings

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#11]
I'm not sure, but maybe we can "group" on/off/unlimited settings and similar into one expression, to not increase the number of entries too much?

Missing:
* `confirm` and `verbose` with `#on_off_unlimited`
* `output-radix` and `input-radix` with `#numeric`
* `height`, `width` and `listsize` with a new `#positive_or_unlimited`  -> `(u(?:n(?:l(?:i(?:m(?:i(?:t(?:e(?:d)?)?)?)?)?)?)?)|\d+)`

**Comment by pirpyn** [comment]
Maybe, i'll test that.

**Comment by pirpyn** [comment]
I've improved the uniformisation of the on off unimited and this looks fairly easy, maybe some day.

**Comment by pirpyn** [comment]
Done with v0.4.2 (7eaa9a7)
