### ISSUE TITLE
condition handling

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#12]
So far we have conditions (for `break if` / `condition` / `if` / `while`) highlighted as `markup.italic.expression.gdb`.
It likely would be useful to:

* have the condition in an own rule we just reference
* actually do some condition handling in there, using already defined patterns like `convenience`, `string`, `numeric` + a new one for operators and a general one - and only have this as `markup.italic.expression.gdb`

this would lead to convenience variables, strings, numbers, ... use the same highlighting they have outside of a condition also within a condition.

**Comment by pirpyn** [comment]
Making the conditonal parsed like the rest is fairly easy, changing the begin group results in 
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/9553e687-d0f2-4be8-9f36-1e9e63b53483)
I did'nt understand your 2nd point though. using some wyiwyg editor, do you have an example of what you want to achieve.

**Comment by GitMensch** [comment]
> Making the conditonal parsed like the rest is fairly easy

Cool! That'S a nice improvement!

Would that be a separate group "expression" that we can use for other places?

**Comment by pirpyn** [comment]
It was the default `#expression` group to be fast. In what case could another group with different parsing be useful ?

**Comment by GitMensch** [comment]
Sounds fine to me, I think this can be closed as soon as this change is distributed.
