### ISSUE TITLE
add `help` and `apropros`

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#14]
I've started this but dropped it from #13 to keep it concise.
Feel free to assign this enhancement issue to me and drop a ping if I did not send in something in the next two weeks.

Syntax: `help` or `apr(opos)`, then separatorm then _one_ word  (actually one can pass multiple words, all but the first one are ignored - should we match this ignored words - and if yes just as italic?)

**Comment by pirpyn** [comment]
Help and apropos seems interactive. Is it worth the time to integrate them in the language ? Do you have some example of a .gdb script with a help or apropos command ?

**Comment by GitMensch** [comment]
They are commonly used in validation of arguments passed to use defined functions. If validation fails one of those may be called from within the defined command.

**Comment by GitMensch** [comment]
One example that shows the use of `help` on input validation of a `define`d function (GH search will show more):
https://raw.githubusercontent.com/Wallacoloo/printipi/master/stl-views.gdb

(note: that sample highlights quite nice, only `help`, `call` and `whatis` don't; and `define` - but that is tracked in #13 already)

**Comment by pirpyn** [comment]
Done apropos & partially for help,
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/c4f1b8aa-e394-4f3a-8d3a-8217c0807948)
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/3d3b213a-4b57-4555-bee0-c70dd169f763)

**Comment by GitMensch** [comment]
Thanks! I'll likely drop a note if something else shows up, otherwise it is mostly #12 that seems to be "open".
