### ISSUE TITLE
add `shell` and `pipe` commands

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#17]
`!` or `she(ll)` + to end of line with shell commands
`|` or `pip(e)` + normal commands + `|` + to end of line with shell commands

adding it may un-break (at least at end of line) the following example, too:

```gdb
	set logging off
	shell target="$(/usr/bin/head -1 /tmp/gdb-objc_symbols | /usr/bin/head -1 | /usr/bin/awk -F '"' '{ print $2 }')"; objc-symbols "$target" | SymTabCreator -o /tmp/gdb-symtab
	set logging on
```

**Comment by pirpyn** [comment]
Done, the wrong rendering was also a bug in the strings begin / end matcher
Now renders as
![image](https://user-images.githubusercontent.com/13225186/219055375-2ee770fa-2785-4f24-a10e-d146b975f3d8.png)
