### ISSUE TITLE
add `target` command with all its sub-options

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#18]
not a high priority, feel free to assign this to me

**Comment by pirpyn** [comment]
Added project to track subcommands completion. Doc at https://sourceware.org/gdb/onlinedocs/gdb/Target-Commands.html#index-target

**Comment by pirpyn** [comment]
Sub option in the doc and with my gdb mismatch : doc shows target sim, my gdb dont know about this sub option.
What target command are you using the most @GitMensch  ?

**Comment by GitMensch** [comment]
remote and extended-remote are likely the most used ones

**Comment by GitMensch** [comment]
... actually all but sim...
