### ISSUE TITLE
add scoped commands `loop_break` + `loop_continue` and `silent`

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#21]
The loop ones are only valid within `while`, the `silent` only in `commands` (other than `dont-repeat`, for example).
I may try to add those some day to their block definitions.

**Comment by pirpyn** [comment]
Silent is difficult. According to doc, its onlyu meaningfull if its the first instruction after the commands.
I have no idea how to do that with regex and begin matchers, as i tried both `\n` and `\\s` to include the linbreak in the commands match and check for silent on the lien after but it didn't work

**Comment by GitMensch** [comment]
Yes, it is only meaningful there, but if I remember correctly it isn't an error otherwise, so may be included as just a normal command.
