### ISSUE TITLE
add catchpoints

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#24]
see https://sourceware.org/gdb/onlinedocs/gdb/Set-Catchpoints.html

```gdb
catch throw
catch exception unhandled
tcatch fork
```

**Comment by pirpyn** [comment]
Done with c3f15fc
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/6b8a1aef-f27f-4993-903e-bd2fb652eed9)
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/8e2b4b82-8bd8-470a-9e63-93d101aa39a7)
