### ISSUE TITLE
info (+whatis/ptype) command

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#25]
partially described in https://sourceware.org/gdb/onlinedocs/gdb/Symbols.html#index-local-variables

```gdb
info locals
info symbol my_exec
info scope main.cpp:12
ptype var
whatis var
```

**Comment by pirpyn** [comment]
Will be done today

**Comment by pirpyn** [comment]
Done partially with the lastest tag v0.3.3 
info scope, address, symbol, locals types
