### ISSUE TITLE
FR: support for 'server' prefix

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#28]
A script many contain `server` before _any_ command - and that' actually quite useful.
https://sourceware.org/gdb/onlinedocs/gdb/Server-Prefix.html

But I have no clue how to add something that you can place before any command and have the commands highlighted correctly.

**Comment by pirpyn** [comment]
With some modification by removing the string start regex anchor and putting the `#command` group as an include to the server command, it could be done.

**Comment by pirpyn** [comment]
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/d23c9b49-5e85-487a-a32e-b9cf9361a551)
Merge in master, and will be added in next release
