### ISSUE TITLE
FR: support for 'quit' command

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#29]
Often used for "automated" GDB scripting. The first result I've got on SO that uses this:

```gdb
set pagination off
set logging file gdb.txt
set logging on
file a.out
b f
commands
backtrace
continue
end
info breakpoints
r
set logging off
quit
```

**Comment by pirpyn** [comment]
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/7d4aeb18-27da-46b3-aec5-ccfe3867b881)
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/add30fbd-caa2-44c5-8a36-dc63ce375d5d)
