### ISSUE TITLE
FR: support for 'call' command

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#30]
... another one quite useful in GDB scripts; you can use `print` nearly identical, see https://sourceware.org/gdb/onlinedocs/gdb/Calling.html#Calling

**Comment by pirpyn** [comment]
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/4558799b-2088-4a61-b1e7-9f1bf2dd5433)
