### ISSUE TITLE
on/off should be word limited

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#34]
no priority at all, just stumbled over this when checking the issue14 test:

```gdb
set detach-on-fork off
```

the off should be highlighted, the "on" not, because it is part of a word, not a word on its own, currently both are highlighted

**Comment by pirpyn** [comment]
this is a side effect of having on-off parsed anywhere, and - being a word boundary for the regex engine.
Since set starts a group, anything after is parsed independantly, and detach on and fork are seen a separate

**Comment by pirpyn** [comment]
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/8997dcfe-5bad-4486-9d0d-ffc0cba7c510)

**Comment by pirpyn** [comment]
First lookahead / lookbehind use. Thanks for the issues, it keeps me learning regex

**Comment by GitMensch** [comment]
That's possibly a good reason for another release :-)
