### ISSUE TITLE
FR: option for `break`/`tbreak` : `-force-condition if`

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#37]
https://sourceware.org/gdb/current/onlinedocs/gdb.html/Set-Breaks.html#Set-Breaks

`break -force-condition if something`
`break 123 -force-condition if something`

low-priority, just stumbled over that.

Note: Given my tests `-force-condition` may not be abbreviated and must directly be placed before the `if`.

**Comment by pirpyn** [comment]
Done, will be pushed soon
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/fb066a0a-221e-40d1-bc3a-66924b113776)
