### ISSUE TITLE
FR: support for explicit locations

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#38]
Currently the locations are used at least for `break`/`tbreak`/`until` and the returning name is `markup.underline.link.location.gdb`.
The current regex is `(?:[ \t]+([^ \t]+))`.

This regex matches all of the [Linespec-Locations](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Linespec-Locations.html#Linespec-Locations):
`funcname` or `label`
`funcname:label`
`some.source:funcame`
`123`
`+5`
`-6`
`some.source:123`
and also the [Address-Locations](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Address-Locations.html#Address-Locations)
`0x123546` (simple)
`0x123546+d1212*55` (complex: expression, but only without white space)

So far it doesn't match the [Explicit-Locations](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Explicit-Locations.html#Explicit-Locations) which can be combined in any order:
` -function prog_ -label ENTRY_prog -source some.source`

I suggest to add new group "#location" and use that for every expected place, then add the explicit locations in there.

**Comment by pirpyn** [comment]
Good idea, will work on it next Monday.

**Comment by pirpyn** [comment]
That was a heavier work than planned. 
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/04b47aa2-e841-47ae-af6d-15014e652a2b)
