### ISSUE TITLE
VSIX should not package test files

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#39]
currently the following "additional" / unneeded files are packaged and therefore installed:

* .github
* hello_world
* scripts
* tests

Please consider adjusting the vsix building to drop those.

**Comment by pirpyn** [comment]
latest commit should solve that, next release should be fine, this issue will stay opened until next release to check the status

**Comment by pirpyn** [comment]
The packages now only contain
![image](https://github.com/pirpyn/gdb-syntax-vscode/assets/13225186/85ce8b81-9191-4eda-9b3c-ecf1764304d9)

**Comment by GitMensch** [comment]
Cool, this way the extension got even ~6.5% smaller ;-)
