### ISSUE TITLE
FR: add settings for disassemble and memory randomization

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#40]
**Which command do you need**
`set` command, the settings:
* `disable-randomization` (boolean: on/off/auto)
* `disassemble-next-line`  (boolean: on/off/auto)
* `disassembly-flavor` (att, intel)

**Describe the rendering you'd like**
common settings like https://github.com/pirpyn/gdb-syntax-vscode/commit/8c49eaa36c9feb0e1ead7f1d43012ce920f1e383

**Examples & tests**
> `set disable-randomization off`
> `set disassemble-next-line on`
> `set disassembley-favor intel`

**Comment by pirpyn** [comment]
Added and published

**Comment by GitMensch** [comment]
That was fast - thanks!

**Comment by pirpyn** [comment]
You're welcome. It was a matter of luck. I'm on vacation and happened to be in front on my pc at the moment.
