### ISSUE TITLE
print settings

### ISSUE THREAD

**Issue by GitMensch** [pirpyn/gdb-syntax-vscode#6]
When inspecting some of my scripts I've found some print settings be not recognized. Example:

```gdb
set print elements 250
set print repeats 20
set print frame-arguments all
```

Also python scripts can add their own sub-settings, in an example I use:

```gdb
set print cprint-pretty-display on
set print cprint-display-mode 6
```

I suggest to:
* add the three first ones
* add a last "catch-all" for everything not matched yet, so more or less `set print .*` with the last group to be colored in either white or yellow

What do you think?

**Comment by pirpyn** [comment]
I'll have look for the first 3. I never use python script so for the later i don't know yet. I'll have a look tomorrow (10 pm here)

**Comment by GitMensch** [comment]
python scripting is _really_ cool, I only came back to python because of GDB :-)

it is much easier and more powerful to define own commands, own parameters, ... that way; which is very helpful when inspecting linked lists, structures, ... or for just adding some new commands.

Hm, and that also reminds me, that parameters can also be named without a prefix, so for both that case and "parameters we just have not yet added explicit":

* add a last "catch-all" for everything not matched yet with the print prefix, so more or less "set print .*" with the last group to be colored in either white or yellow
* add a last "catch-all" for everything not matched yet, so more or less "set .*" with the last group to be colored in either white or yellow


Just for a python script example - you find something I re-tuned from time to time and consider now done (saved as gdb_autonextstep.py), handles stopping on break/watchpoints/signals/process end or ctrl+c, found at https://stackoverflow.com/questions/6947389/67470615#67470615 (second script)

**Comment by pirpyn** [comment]
I've dealt with the first 3 items and the cprint-* renders as white.
![image](https://user-images.githubusercontent.com/13225186/217218395-48b346ff-d092-4b71-9408-483cad7d1340.png)
I'll check later to add theses cprint option.

If you have time, you can propose a PR. Note, the readme now states that PR shall include a tests/script.gdb to check rendering.

**Comment by GitMensch** [comment]
> I'll check later to add theses cprint option.

I think that's not useful, because that's "user written code" which could be "unlimited" - rendering "unknown in white" is perfectly fine. One thing that _may_ be added would be to match on/off/auto and integer/unlimited at the end.

> add a last "catch-all" for everything not matched yet, so more or less "set .*" with the last group to be colored in either white or yellow

Did you do that already, too?

**Comment by pirpyn** [comment]
I didn't do it, its just a consequence of using begin end matchers : we match set print, so its colored and if what follows is not matched its stays white.

**Comment by GitMensch** [comment]
> I didn't do it, its just a consequence of using begin end matchers : we match set print, so its colored and if what follows is not matched its stays white.

I see, so I'll try to handle the same for simple "set" later (possibly "in two weeks"), this way things like `set auto-speed 19` from the shown gdb extension script will get partially matched.
